name: CI Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  workflow_call:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: true
    env:
      testDirectory: market-test/pom.xml
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Editor checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - run: editorconfig-checker -verbose --no-color

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build source
        shell: bash
        run: |
          cd market-test
          mvn compile exec:java -Dexec.mainClass="com.axonivy.market.CreateBundle" -Dmaven.plugin.validation=none -Duser.home=/tmp -DskipTests
          mvn verify -P json.schema -Dmaven.plugin.validation=none -Duser.home=/tmp -DfailFast=true
          cd ../

      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            **/target/schema/market/*/*.json

      - name: Public test report
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: success() || failure()
        with:
          files: "**/target/surefire-reports/**/*.xml"

      - name: Clean up
        run: |
          rm -rf *
